### ISSUE TITLE
Consider update to 2.2.0?

### ISSUE THREAD

**Issue by simsilver** [flathub/com.github.gmg137.netease-cloud-music-gtk#6]
It's the latest release and there is a commit https://github.com/gmg137/netease-cloud-music-gtk/commit/f93e82f88c7fc375162f0a00e858c266e34f0c4b makes the player skip 30s vip songs

**Comment by catsout** [comment]
pr welcome.

**Comment by simsilver** [comment]
I did a simple update at https://github.com/simsilver/com.github.gmg137.netease-cloud-music-gtk/commit/796bd251ac76247c38736498e1088e0d90764330, right now it failed with message "thread 'main' panicked at src/gui/discover.rs:120:30:
Template child with id `carousel` has incompatible type. XML has GtkFlowBox, struct has AdwCarousel", I'm not familiar with gtk4, so may check it later.

**Comment by simsilver** [comment]
regenerate Cargo.lock fix it, I'll make a pr.

**Comment by MasterTOTO** [comment]
now i install it from flathub, it said :thread 'main' panicked at src/gui/discover.rs:117:30,can you fix it？Thanks a lot

**Comment by simsilver** [comment]
I did install from "flatpak install https://dl.flathub.org/build-repo/64565/com.github.gmg137.netease-cloud-music-gtk.flatpakref" and it works with "flatpak run com.github.gmg137.netease-cloud-music-gtk", but it launch failed with typing netease in gnome overview. I'm not familiar with flatpak, and the desktop file seems normal as other flatpak apps, so I left this behind……

> now i install it from flathub, it said :thread 'main' panicked at src/gui/discover.rs:117:30,can you fix it？Thanks a lot

how did you launch it?

**Comment by MasterTOTO** [comment]
> I did install from "flatpak install https://dl.flathub.org/build-repo/64565/com.github.gmg137.netease-cloud-music-gtk.flatpakref" and it works with "flatpak run com.github.gmg137.netease-cloud-music-gtk", but it launch failed with typing netease in gnome overview. I'm not familiar with flatpak, and the desktop file seems normal as other flatpak apps, so I left this behind……
> 
> > now i install it from flathub, it said :thread 'main' panicked at src/gui/discover.rs:117:30,can you fix it？Thanks a lot
> 
> how did you launch it?

I tried reinstall it from https://dl.flathub.org/build-repo/64565/com.github.gmg137.netease-cloud-music-gtk.flatpakref. It works all well.I can start it from desktop in gnome. Maybe you can try reboot your device？

**Comment by simsilver** [comment]
Finally found out it's because my local broken native installation…

**Comment by MasterTOTO** [comment]
Thanks for what you did, Can you upload the new version to FlatHub？

**Comment by simsilver** [comment]
> Thanks for what you did, Can you upload the new version to FlatHub？

I think that we should wait for the pr to be merged
